[package]
name = "polyfuse-async-std"
version = "0.1.0-dev"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[dependencies]
polyfuse = { version = "0.4.0-dev", path = "../polyfuse" }

async-io = "1.2"
futures = "0.3"
