regular_task_template: &REGULAR_TASK_TEMPLATE
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_PR != ''

task:
  << : *REGULAR_TASK_TEMPLATE
  name: FreeBSD
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock || echo ""
  setup_script:
    - pkg install -y pkgconf fusefs-libs
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all --all-targets --verbose
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all --verbose
  before_cache_script:
    - rm -rf $CARGO_HOME/registry/index
