[package]
name = "fuse-async"
version = "0.1.0"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[dependencies]
fuse-async-abi = { version = "0.1.0", path = "fuse-async-abi" }
fuse-async-io = { version = "0.1.0", path = "fuse-async-io" }

async-trait = "0.1"
futures-preview = { version = "0.3.0-alpha.18", features = ["nightly", "async-await"] }
libc = "0.2"
log = "0.4"
tokio-io = { version = "0.2.0-alpha.1", features = ["util"] }
tokio-net = { version = "0.2.0-alpha.1", features = ["signal"] }

[workspace]
members = [
  ".",
  "fuse-async-abi",
  "fuse-async-channel",
  "fuse-async-io",

  "examples/null",
]
