[package]
name = "fuse-async"
version = "0.1.0"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
futures-preview = { version = "0.3.0-alpha.19", features = ["unstable", "async-await"] }
libc = "0.2"
log = "0.4"
memoffset = "0.5"
smallvec = "0.6"

[dependencies.tokio-net]
version = "0.2.0-alpha.1"
optional = true
features = ["signal"]
default-features = false

[dependencies.fuse-async-channel]
version = "0.1.0"
path = "fuse-async-channel"
optional = true

[features]
default = ["tokio", "channel"]
channel = ["fuse-async-channel"]
tokio = ["tokio-net", "fuse-async-channel/tokio"]

[workspace]
members = [
  ".",
  "fuse-async-channel",

  "examples/null",
]
