[package]
name = "tokio-fuse"
version = "0.1.0"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
bitflags = "1.2"
async-trait = "0.1"
futures-preview = { version = "0.3.0-alpha.18", features = ["nightly", "async-await"] }
libc = "0.2"
log = "0.4"
mio = "0.6"
tokio-io = { version = "0.2.0-alpha.1", features = ["util"] }
tokio-net = { version = "0.2.0-alpha.1", features = ["signal"] }

[build-dependencies]
bindgen = "0.51"

[workspace]
members = [
  ".",
  "tokio-fuse-channel",
  "examples/null",
]
