[package]
name = "fuse-async"
version = "0.1.0"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[dependencies]
fuse-async-abi = { version = "0.1.0", path = "fuse-async-abi" }

async-trait = "0.1"
futures-preview = { version = "0.3.0-alpha.18", features = ["nightly", "async-await"] }
libc = "0.2"
log = "0.4"

[dependencies.tokio-net]
version = "0.2.0-alpha.1"
optional = true
features = ["signal"]
default-features = false

[features]
default = ["tokio"]
tokio = ["tokio-net"]

[workspace]
members = [
  ".",
  "fuse-async-abi",
  "fuse-async-channel",

  "examples/null",
]
