[package]
name = "polyfuse"
version = "0.4.0-dev"
description = "A FUSE (Filesystem in Userspace) library for Rust."
authors = [ "Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>" ]
repository = "https://github.com/ubnt-intrepid/polyfuse.git"
license = "MIT OR Apache-2.0"
edition = "2018"
readme = "README.md"
categories = [ "filesystem" ]
keywords = [ "fuse", "filesystem", "async", "futures" ]

[dependencies]
polyfuse-kernel = { version = "0.1.0-dev", path = "../polyfuse-kernel" }

async-io = "1.2"
bitflags = "1.2"
futures = "0.3"
libc = "0.2"
paste = "1"
smallvec = "1.4"
tracing = "0.1"
