[package]
name = "polyfuse"
version = "0.4.0-dev"
description = "A FUSE (Filesystem in Userspace) library for Rust."
authors = [ "Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>" ]
repository = "https://github.com/ubnt-intrepid/polyfuse.git"
license = "MIT OR Apache-2.0"
edition = "2018"
readme = "README.md"
categories = [ "filesystem" ]
keywords = [ "fuse", "filesystem", "async", "futures" ]
exclude = [ "systest/**/*" ]

[dependencies]
futures = "0.3"
paste = "1"

[dev-dependencies]
version-sync = "0.8"
