[package]
name = "polyfuse-xtask"
version = "0.0.0" # never publish
publish = false
edition = "2018"

[dependencies]
anyhow = "1"
pico-args = "0.3"

[dependencies.cargo-husky]
version = "1.5"
default-features = false
features = [ "user-hooks" ]
