[package]
name = "fuse-async-abi"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
bitflags = "1.2"
libc = "0.2"

[build-dependencies]
bindgen = "0.51"
