[package]
name = "polyfuse-example-async-std-support"
version = "0.0.0" # never publish
publish = false
edition = "2018"

[dependencies]
polyfuse = { path = "../../crates/polyfuse" }

async-io = "1.2"
async-std = { version = ">=1.7.0", features = [ "unstable" ] }
futures = "0.3"
